"""
requirements.lock 存在性断言 —— 防止 requirements.txt 改动后忘记重生成 lock。

lock 文件由 `uv pip compile backend/requirements.txt -o backend/requirements.lock
--generate-hashes` 生成，锁定所有传递依赖 + sha256 哈希，供本地和 audit
精确复现构建（Dockerfile 不用 lock，保留 HF Spaces 自动跟进安全 patch 的弹性）。
"""

from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
LOCK_FILE = ROOT / "backend" / "requirements.lock"
REQUIREMENTS_FILE = ROOT / "backend" / "requirements.txt"


def test_lock_file_exists():
    assert LOCK_FILE.is_file(), (
        f"{LOCK_FILE} 不存在。"
        f"运行 `uv pip compile backend/requirements.txt "
        f"-o backend/requirements.lock --generate-hashes` 重新生成。"
    )


@pytest.fixture(scope="module")
def lock_content() -> str:
    return LOCK_FILE.read_text(encoding="utf-8")


@pytest.mark.parametrize("pkg", ["fastapi", "uvicorn", "pydantic", "openai"])
def test_lock_contains_direct_dependency(lock_content: str, pkg: str):
    """直接依赖必须出现在 lock 里（以 `<pkg>==` 形式）。"""
    assert f"\n{pkg}==" in lock_content or lock_content.startswith(f"{pkg}=="), (
        f"lock 文件中找不到直接依赖 {pkg}==..."
    )


def test_lock_has_hashes(lock_content: str):
    """每个包都必须带 --hash=sha256: 校验，否则 --require-hashes 装不了。"""
    hash_count = lock_content.count("--hash=sha256:")
    assert hash_count >= 20, (
        f"lock 文件 --hash 标记数异常（{hash_count} < 20）。"
        f"用 --generate-hashes 重新生成。"
    )


def test_lock_header_autogenerated(lock_content: str):
    """保留 uv 自动生成头部注释，提醒 reviewer 不要手改 lock。"""
    assert "autogenerated by uv" in lock_content, (
        "lock 文件缺少 `autogenerated by uv` 头部。"
        "该文件应由 uv pip compile 自动生成，不手改。"
    )
