"""
requirements.lock 契约断言 —— 防止 requirements.txt / lock 漂移。

lock 文件由 `uv pip compile backend/requirements.txt -o backend/requirements.lock
--generate-hashes` 生成，用途是**本地开发复现 + 审计基线**（不参与生产部署）：
Dockerfile / HF Spaces 仍走 `pip install -r requirements.txt`，保留自动跟进
安全 patch 的弹性。

本文件断言：
- 直接依赖在 lock 里（4 条参数化）
- `uvicorn[standard]` 的 extras 展平为独立 pinned 条目（Codex 第十轮 review F1
  tripwire：把 uv pip compile 展平 extras 的隐式约定变成显式契约）
- 每个包都带 sha256 哈希
- 保留 `autogenerated by uv` 头部（防手改）
"""

from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
LOCK_FILE = ROOT / "backend" / "requirements.lock"
REQUIREMENTS_FILE = ROOT / "backend" / "requirements.txt"


def test_lock_file_exists():
    assert LOCK_FILE.is_file(), (
        f"{LOCK_FILE} 不存在。"
        f"运行 `uv pip compile backend/requirements.txt "
        f"-o backend/requirements.lock --generate-hashes` 重新生成。"
    )


@pytest.fixture(scope="module")
def lock_content() -> str:
    return LOCK_FILE.read_text(encoding="utf-8")


@pytest.mark.parametrize("pkg", ["fastapi", "uvicorn", "pydantic", "openai"])
def test_lock_contains_direct_dependency(lock_content: str, pkg: str):
    """直接依赖必须出现在 lock 里（以 `<pkg>==` 形式）。"""
    assert f"\n{pkg}==" in lock_content or lock_content.startswith(f"{pkg}=="), (
        f"lock 文件中找不到直接依赖 {pkg}==..."
    )


def test_lock_has_hashes(lock_content: str):
    """每个包都必须带 --hash=sha256: 校验，否则 --require-hashes 装不了。"""
    hash_count = lock_content.count("--hash=sha256:")
    assert hash_count >= 20, (
        f"lock 文件 --hash 标记数异常（{hash_count} < 20）。"
        f"用 --generate-hashes 重新生成。"
    )


def test_lock_header_autogenerated(lock_content: str):
    """保留 uv 自动生成头部注释，提醒 reviewer 不要手改 lock。"""
    assert "autogenerated by uv" in lock_content, (
        "lock 文件缺少 `autogenerated by uv` 头部。"
        "该文件应由 uv pip compile 自动生成，不手改。"
    )


# ----------------------------------------------------------------
# Codex 第十轮 adversarial review F1 tripwire
# ----------------------------------------------------------------
# Codex 指出 lock 里 uvicorn 丢了 [standard] 标记。事实核验：
#   - uv pip compile 把 extras 展平为独立 pinned 条目是 pip-tools 生态标准行为
#   - httptools / uvloop / watchfiles / websockets 作为独立包都在 lock 里
#   - pip --require-hashes -r lock 装出来环境 == uvicorn[standard] 等价
# 所以 Codex 说的 "install break" 不成立，severity high 被驳回。
# 但可审计性问题合理——有人读 lock 推不出"直接意图是 [standard]"。
# 下面的 tripwire 把"extras 被展平"的隐式约定变成显式契约，
# 防止将来 requirements.txt / lock 漂移（比如有人改 requirements.txt 但没 regenerate lock）。

# uvicorn[standard] 的 extras 传递依赖（对 uvicorn 0.24+ 有效，向前兼容）
UVICORN_STANDARD_EXTRAS = ["httptools", "uvloop", "watchfiles", "websockets"]


@pytest.mark.parametrize("extra_dep", UVICORN_STANDARD_EXTRAS)
def test_uvicorn_standard_extras_present_in_lock(lock_content: str, extra_dep: str):
    """若 requirements.txt 声明 uvicorn[standard]，lock 应展平所有 standard extras。"""
    req_txt = REQUIREMENTS_FILE.read_text(encoding="utf-8")
    if "uvicorn[standard]" not in req_txt:
        pytest.skip("requirements.txt 未声明 uvicorn[standard]——跳过 extras 检查")
    assert f"\n{extra_dep}==" in lock_content, (
        f"requirements.txt 声明了 uvicorn[standard]，但 lock 里缺 {extra_dep}==。"
        f"uv pip compile 应把 extras 展平为独立条目——"
        f"如果 requirements.txt 改动过，重新运行 "
        f"`uv pip compile backend/requirements.txt -o backend/requirements.lock "
        f"--generate-hashes`。"
    )
